# ПРАКТИКА 4


#### ЗАДАНИЕ

1. Запросить у пользователя количество информационных разрядов и рассчитать для 
него количество проверочных. 

2. Методом Хемминга закодировать произвольную информационную комбинацию, 
заданного размера, построив порождающую и проверочную матрицы.  

3. Внести ошибку в один из разрядов кодового вектора; найти синдром; найти и 
исправить ошибку. 

#### Задание 1 + Отладка функции

In [ ]:
import numpy as np
def generate_generator_matrix(H, n, k):

    #[P^T | I_r]
    r = n - k
    P_T = H[:, :n-r]  # Левая часть H
    I_r = H[:, n-r:]  # Правая часть H (должна быть единичной матрицей)
    
    # Проверяем, что правая часть H — это единичная матрица
    if not np.array_equal(I_r, np.eye(r, dtype=int)):
        raise ValueError("Последние столбцы H должны быть единичной матрицей.")
    
    # Строим порождающую матрицу G = [I_k | P]
    P = P_T.T  # Транспонируем P^T
    I_k = np.eye(k, dtype=int)  # Единичная матрица I_k
    G = np.hstack((I_k, P))  # Объединяем I_k и P
    
    return G

# 7-4
G = [[1, 0, 1, 1, 0, 0, 0],
     [0, 1, 0, 1, 1, 0, 0],
     [0, 0, 1, 0, 1, 1, 0],
     [0, 0, 0, 1, 1, 0, 1]]

message = np.array([1, 1, 0, 1])
code_word = np.dot(message, G) % 2
print("Сообщение:")
print(message)
print("Проверочная матрица H:")
print(H)
print("Порождающая матрица G:")
print(G)
print("Кодовое слово:")
print(code_word)

Сообщение:
[1 1 0 1]
Проверочная матрица H:
[[0 0 0 1 1 0 0]
 [0 1 1 0 0 1 0]
 [1 0 1 0 0 0 1]]
Порождающая матрица G:
[[1, 0, 1, 1, 0, 0, 0], [0, 1, 0, 1, 1, 0, 0], [0, 0, 1, 0, 1, 1, 0], [0, 0, 0, 1, 1, 0, 1]]
Кодовое слово:
[1 1 1 1 0 0 1]


#### Задание 2